CREATE USER dealer
IDENTIFIED BY c4rs
DEFAULT TABLESPACE users
TEMPORARY TABLESPACE temp
QUOTA 10M ON users;

GRANT connect to dealer;
GRANT resource to dealer;
GRANT create session TO dealer;
GRANT create table TO dealer;
GRANT create view TO dealer;

conn dealer/c4rs

CREATE TABLE AUTHENTICATION(
USER_ID INTEGER PRIMARY KEY,
USERNAME VARCHAR2(20),
PASSWORD VARCHAR2(20),
CUSTOMER INTEGER);

INSERT INTO AUTHENTICATION VALUES (1, 'CrazyDave', 'WhereMyCarAt', 0);
INSERT INTO USER_TYPE VALUES (1, 0);

CREATE SEQUENCE ID_GEN
START WITH 2
INCREMENT BY 1;

SELECT * FROM AUTHENTICATION
WHERE USERNAME='CrazyDave';