CREATE USER dealer
IDENTIFIED BY c4rs
DEFAULT TABLESPACE users
TEMPORARY TABLESPACE temp
QUOTA 10M ON users;

GRANT connect to dealer;
GRANT resource to dealer;
GRANT create session TO dealer;
GRANT create table TO dealer;
GRANT create view TO dealer;

conn dealer/c4rs

CREATE TABLE AUTHENTICATION(
USER_ID INTEGER PRIMARY KEY,
USERNAME VARCHAR2(20),
PASSWORD VARCHAR2(20),
CUSTOMER INTEGER);

CREATE TABLE CAR_OWNER(
CAR_ID INTEGER PRIMARY KEY,
USER_ID INTEGER);

CREATE TABLE PENDING_OFFERS(
OFFER_ID INTEGER PRIMARY KEY,
CAR_ID INTEGER,
CUSTOMER_ID INTEGER,
OFFER DECIMAL);

CREATE TABLE ACCEPTED_OFFERS(
CAR_ID INTEGER PRIMARY KEY,
CUSTOMER_ID INTEGER,
MONTHS_LEFT INTEGER,
AMOUNT_OWED DECIMAL);

CREATE TABLE PAYMENT_HISTORY(
TRANSACTION_ID INTEGER PRIMARY KEY,
CAR_ID INTEGER,
USER_ID INTEGER,
AMOUNT_PAID DECIMAL);

INSERT INTO AUTHENTICATION VALUES (1, 'CrazyDave', 'WhereMyCarAt', 0);
INSERT INTO USER_TYPE VALUES (1, 0);

CREATE SEQUENCE ID_GEN
START WITH 2
INCREMENT BY 1;

CREATE SEQUENCE CAR_ID_GEN
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE OFFER_ID_GEN
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE TRANSACTION_ID_GEN
START WITH 1
INCREMENT BY 1;

SELECT * FROM AUTHENTICATION
WHERE USERNAME='CrazyDave';

SELECT * FROM CAR_OWNER WHERE USER_ID=0;